import { VehicleType } from 'gtfs-types';
import type { NetworkConfig } from '../types/config.def.js';

export const NZ: NetworkConfig[] = [
  {
    code: 'NZ-AKL',
    region: 'NZ-AUK',
    networkName: 'AT',
    networkWikidata: 'Q4819567',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://gtfs.at.govt.nz/gtfs.zip',
    },
    licenseWaiverUrl: 'https://osm.wiki/Contributors#Auckland_Transport',
    ignoreRoutes: [
      'HCRU', // private harbour cruise
      'MTAR', // private prebooked waiheke ferry

      // ignore rail busses
      'RBS',
      'RBW',
      'RBO',
      'RBE',
      'RBSX',
      'RBO-A',
      'RBS-A',
      'RBE-A',
      'RBW-A',
      'RBN',
      'RBM',
    ],
    ignoreStops: {
      // britomart stops are messed up since they decommissioned platform 2 & renumbered the rest
      9002: '9001',
      9003: '9001',
      9004: '9001',

      9329: '9328', // swanson platform 2 -> 1
      9508: '9507', // manukau platform 2 -> 1
    },

    operatorMap: {
      'Tranzit Group Ltd': {
        name: 'Tranzit Group',
        wikidata: 'Q55636134',
      },
      'Go Bus': { name: 'Kinetic', wikidata: 'Q85774435' },
      'Ritchies Transport': {
        name: 'Ritchies Transport',
        wikidata: 'Q7336695',
      },
      'Waiheke Bus Company': {
        name: 'Waiheke Bus Company',
        wikidata: 'Q5508281',
      },
      'Explore Group': { name: 'Explore Group', wikidata: 'Q115631528' },
      'SeaLink Pine Harbour': {
        name: 'SeaLink Pine Harbour',
        wikidata: 'Q7439812',
      },
      'Island Direct': { name: 'Island Direct', wikidata: 'Q123290531' },
      'Pavlovich Transport Solutions': {
        name: 'Pavlovich Transport Solutions',
        wikidata: 'Q137175212',
      },
      'New Zealand Bus': { name: 'Kinetic', wikidata: 'Q85774435' },
      'Howick and Eastern': {
        name: 'Howick and Eastern',
        wikidata: 'Q137175102',
      },
      'Bayes Coachlines': {
        name: 'Bayes Coachlines',
        wikidata: 'Q137175096',
      },
      'Mahu City Express': { name: 'Mahu City Express', wikidata: '' },
      'AT Metro Bus': { name: 'AT Metro Bus', wikidata: '' }, // rail replacement busses

      Fullers360: { name: 'Fullers360', wikidata: 'Q5508281' },
      'Belaire Ferries': {
        name: 'Belaire Ferries',
        wikidata: 'Q117328118',
      },
      'SeaLink Travel Group': {
        name: 'SeaLink New Zealand',
        wikidata: 'Q7439812',
      },
      'Waikato Regional Council': {
        name: 'Waikato Regional Council',
        wikidata: 'Q84773951',
      },
      'AT Metro': { name: 'Auckland One Rail', wikidata: 'Q108501777' },
    },
  },
  {
    code: 'NZ-WLG',
    region: 'NZ-WGN',
    networkName: 'Metlink',
    networkWikidata: 'Q7258026',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://static.opendata.metlink.org.nz/v1/gtfs/full.zip',
    },
    licenseWaiverUrl: 'https://osm.wiki/File:Metlink-License-Email.pdf',
    ignoreTags: [
      'colour', // colours are wrong, they've used a generic blue for many bus routes
      'bicycle', // it's wrong, they've set it to 'no' for every bus, train, and ferry
    ],
    ignoreStops: {
      // rural "Fare Zone Boundary" fake stops
      '0001': null,
      '0002': null,
      '0003': null,
      '0004': null,
      '0005': null,
      '0006': null,
    },
    overrideTransportModes: {
      // school busses
      309: VehicleType.SCHOOL_BUS,
      313: VehicleType.SCHOOL_BUS,
      315: VehicleType.SCHOOL_BUS,
      366: VehicleType.SCHOOL_BUS,
      402: VehicleType.SCHOOL_BUS,
      421: VehicleType.SCHOOL_BUS,
      429: VehicleType.SCHOOL_BUS,
      430: VehicleType.SCHOOL_BUS,
      440: VehicleType.SCHOOL_BUS,
      441: VehicleType.SCHOOL_BUS,
      442: VehicleType.SCHOOL_BUS,
      444: VehicleType.SCHOOL_BUS,
      445: VehicleType.SCHOOL_BUS,
      460: VehicleType.SCHOOL_BUS,
      461: VehicleType.SCHOOL_BUS,
      465: VehicleType.SCHOOL_BUS,
      500: VehicleType.SCHOOL_BUS,
      501: VehicleType.SCHOOL_BUS,
      505: VehicleType.SCHOOL_BUS,
      507: VehicleType.SCHOOL_BUS,
      508: VehicleType.SCHOOL_BUS,
      509: VehicleType.SCHOOL_BUS,
      510: VehicleType.SCHOOL_BUS,
      512: VehicleType.SCHOOL_BUS,
      530: VehicleType.SCHOOL_BUS,
      611: VehicleType.SCHOOL_BUS,
      612: VehicleType.SCHOOL_BUS,
      614: VehicleType.SCHOOL_BUS,
      615: VehicleType.SCHOOL_BUS,
      616: VehicleType.SCHOOL_BUS,
      617: VehicleType.SCHOOL_BUS,
      619: VehicleType.SCHOOL_BUS,
      621: VehicleType.SCHOOL_BUS,
      623: VehicleType.SCHOOL_BUS,
      625: VehicleType.SCHOOL_BUS,
      627: VehicleType.SCHOOL_BUS,
      633: VehicleType.SCHOOL_BUS,
      634: VehicleType.SCHOOL_BUS,
      635: VehicleType.SCHOOL_BUS,
      646: VehicleType.SCHOOL_BUS,
      648: VehicleType.SCHOOL_BUS,
      654: VehicleType.SCHOOL_BUS,
      667: VehicleType.SCHOOL_BUS,
      673: VehicleType.SCHOOL_BUS,
      674: VehicleType.SCHOOL_BUS,
      677: VehicleType.SCHOOL_BUS,
      680: VehicleType.SCHOOL_BUS,
      681: VehicleType.SCHOOL_BUS,
      682: VehicleType.SCHOOL_BUS,
      685: VehicleType.SCHOOL_BUS,
      704: VehicleType.SCHOOL_BUS,
      711: VehicleType.SCHOOL_BUS,
      712: VehicleType.SCHOOL_BUS,
      715: VehicleType.SCHOOL_BUS,
      716: VehicleType.SCHOOL_BUS,
      717: VehicleType.SCHOOL_BUS,
      718: VehicleType.SCHOOL_BUS,
      719: VehicleType.SCHOOL_BUS,
      721: VehicleType.SCHOOL_BUS,
      722: VehicleType.SCHOOL_BUS,
      725: VehicleType.SCHOOL_BUS,
      726: VehicleType.SCHOOL_BUS,
      730: VehicleType.SCHOOL_BUS,
      731: VehicleType.SCHOOL_BUS,
      732: VehicleType.SCHOOL_BUS,
      734: VehicleType.SCHOOL_BUS,
      736: VehicleType.SCHOOL_BUS,
      737: VehicleType.SCHOOL_BUS,
      739: VehicleType.SCHOOL_BUS,
      740: VehicleType.SCHOOL_BUS,
      742: VehicleType.SCHOOL_BUS,
      743: VehicleType.SCHOOL_BUS,
      744: VehicleType.SCHOOL_BUS,
      745: VehicleType.SCHOOL_BUS,
      746: VehicleType.SCHOOL_BUS,
      751: VehicleType.SCHOOL_BUS,
      753: VehicleType.SCHOOL_BUS,
      754: VehicleType.SCHOOL_BUS,
      755: VehicleType.SCHOOL_BUS,
      758: VehicleType.SCHOOL_BUS,
      760: VehicleType.SCHOOL_BUS,
      762: VehicleType.SCHOOL_BUS,
      764: VehicleType.SCHOOL_BUS,
      767: VehicleType.SCHOOL_BUS,
      768: VehicleType.SCHOOL_BUS,
      769: VehicleType.SCHOOL_BUS,
      770: VehicleType.SCHOOL_BUS,
      774: VehicleType.SCHOOL_BUS,
      775: VehicleType.SCHOOL_BUS,
      776: VehicleType.SCHOOL_BUS,
      784: VehicleType.SCHOOL_BUS,
      791: VehicleType.SCHOOL_BUS,
      823: VehicleType.SCHOOL_BUS,
      825: VehicleType.SCHOOL_BUS,
      828: VehicleType.SCHOOL_BUS,
      842: VehicleType.SCHOOL_BUS,
      843: VehicleType.SCHOOL_BUS,
      848: VehicleType.SCHOOL_BUS,
      849: VehicleType.SCHOOL_BUS,
      852: VehicleType.SCHOOL_BUS,
      853: VehicleType.SCHOOL_BUS,
      854: VehicleType.SCHOOL_BUS,
      855: VehicleType.SCHOOL_BUS,
      860: VehicleType.SCHOOL_BUS,
      866: VehicleType.SCHOOL_BUS,
      868: VehicleType.SCHOOL_BUS,
      874: VehicleType.SCHOOL_BUS,
      886: VehicleType.SCHOOL_BUS,
      887: VehicleType.SCHOOL_BUS,
      888: VehicleType.SCHOOL_BUS,
      901: VehicleType.SCHOOL_BUS,
      906: VehicleType.SCHOOL_BUS,
      911: VehicleType.SCHOOL_BUS,
      915: VehicleType.SCHOOL_BUS,
      916: VehicleType.SCHOOL_BUS,
      929: VehicleType.SCHOOL_BUS,
      930: VehicleType.SCHOOL_BUS,
      931: VehicleType.SCHOOL_BUS,
      935: VehicleType.SCHOOL_BUS,
      951: VehicleType.SCHOOL_BUS,
      953: VehicleType.SCHOOL_BUS,
      955: VehicleType.SCHOOL_BUS,
    },
    operatorMap: {
      'Metlink Rail': {
        name: 'Transdev Wellington',
        wikidata: 'Q24088909',
      },
      'Wellington Cable Car': {
        name: 'Wellington Cable Car',
        wikidata: 'Q954278',
      },
      Uzabus: { name: 'Uzabus', wikidata: '' },
      'Uzabus (Horizons)': { name: 'Uzabus', wikidata: '' },
      'Mana Coach Services Limited': {
        name: 'Mana Newlands Coach Services',
        wikidata: '',
      },
      'Tranzit Coachlines': {
        name: 'Tranzit Group',
        wikidata: 'Q55636134',
      },
      'NZ Bus': { name: 'NZ Bus', wikidata: 'Q6956272' },
      'East By West Ferry': {
        name: 'East By West',
        wikidata: 'Q117461595',
      },
    },
  },
  {
    code: 'NZ-WKT',
    region: 'NZ-WKO',
    networkName: 'BUSIT',
    networkWikidata: 'Q24998601',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://wrcscheduledata.blob.core.windows.net/wrcgtfs/busit-nz-public.zip',
    },
    operatorMap: {
      Busit: { name: '', wikidata: '' },
    },
    overrideTransportModes: {
      HUIA: VehicleType.REGIONAL_RAIL,
    },
    licenseWaiverUrl: 'https://osm.wiki/File:WRC-License-Email.pdf',
  },
  {
    code: 'NZ-BOP',
    region: 'NZ-BOP',
    networkName: 'BayBus',
    networkWikidata: 'Q112189811',
    gtfsSource: {
      mode: 'automatic',
      // eslint-disable-next-line unicorn/prefer-https -- website only supports http
      url: 'http://gtfs.dynamis.live/boprc/prod/boprc-nz.zip',
    },
    licenseWaiverUrl:
      'https://osm.wiki/Contributors#Bay_of_Plenty_Regional_Council',
  },
  {
    code: 'NZ-MWT',
    region: 'NZ-MWT',
    networkName: 'Horizons',
    networkWikidata: 'Q124314259',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://www.horizons.govt.nz/HRC/media/Data/files/tranzit/HRC_GTFS_Production.zip',
    },
    licenseWaiverUrl: 'https://osm.wiki/Contributors#Horizons_Regional_Council',
  },
  {
    code: 'NZ-TKI',
    region: 'NZ-TKI',
    networkName: 'Taranaki Regional Council',
    networkWikidata: 'Q16926647',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://data.trilliumtransit.com/gtfs/trc-nz/trc-nz.zip',
    },
    includeAllStops: true,
    useStopId: true,
    operatorMap: {
      Tranzit: { name: 'Tranzit Group', wikidata: 'Q55636134' },
      'Pickering Motors': {
        name: 'Pickering Motors',
        wikidata: 'Q134292429',
      },
      'Weir Bros': { name: 'Weir Bros', wikidata: 'Q16926647' },
    },
    licenseWaiverUrl: 'https://osm.wiki/Contributors#Taranaki_Regional_Council',
  },
  {
    code: 'NZ-NSN',
    region: 'NZ-NSN',
    networkName: 'eBus',
    networkWikidata: 'Q133818760',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://data.trilliumtransit.com/gtfs/nsn-nz/nsn-nz.zip',
    },
    licenseWaiverUrl: 'https://osm.wiki/File:NZ_Nelson_CC-4.0_Waiver.pdf',
  },
  {
    code: 'NZ-CHC',
    region: 'NZ-CAN',
    networkName: 'Metro Christchurch',
    networkWikidata: 'Q7258007',
    gtfsSource: {
      mode: 'manual',
      url: 'https://apis.metroinfo.co.nz/rti/gtfs/v1/gtfs.zip',
    },
    licenseWaiverUrl: 'https://osm.wiki/Contributors#Environment_Canterbury',
  },
  {
    code: 'NZ-NTH',
    region: 'NZ-NTL',
    networkName: 'Citylink Whangārei',
    networkWikidata: 'Q112189837',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://data.trilliumtransit.com/gtfs/nrc-nz/nrc-nz.zip',
    },
    licenseWaiverUrl: undefined,
  },
  {
    code: 'NZ-HWK',
    region: 'NZ-HKB',
    networkName: 'goBay',
    networkWikidata: 'Q112189822',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://data.trilliumtransit.com/gtfs/hbrc-nz/hbrc-nz.zip',
    },
    licenseWaiverUrl: undefined,
  },
  // Gisborne has bus services but no GTFS feed
  // Southland has bus services but no GTFS feed
  // Marlborough has bus services but no GTFS feed
  // West Coast has no public transport
  // Chatham Islands have no public transport
  {
    code: 'NZ-OTG',
    region: 'NZ-OTA',
    networkName: 'Otago Regional Council',
    networkWikidata: 'Q7108351',
    gtfsSource: {
      mode: 'automatic',
      url: 'https://www.orc.govt.nz/transit/google_transit.zip',
    },
    licenseWaiverUrl: 'https://osm.wiki/File:ORC-License-Email.pdf',
  },
];
