import type { OsmPatchFeature as GeoJsonFeature } from 'osm-api';
import { geoCentroid as getFirstCoord } from 'd3-geo';
import type {
  Ctx,
  HandlerReturnWithBBox,
  OutputLayer,
} from '../../types/index.js';
import { MAX_ITEMS_PER_DATASET } from '../../constants/defaults.js';
import { calcBBox } from '../../common/calcBBox.js';
import { getSector } from '../../common/getSector.js';
import { bboxToPolygon } from '../../common/bboxToPolygon.js';

export function splitUntilSmallEnough(
  ctx: Ctx,
  name: string,
  metadata: Omit<OutputLayer, 'features' | 'bbox' | 'sectorIds'>,
  features: GeoJsonFeature[],
  depth = 0,
): HandlerReturnWithBBox {
  if (!features.length) return {};

  const bbox = calcBBox(features);
  const sectorIds = getSector(
    bboxToPolygon(bbox),
    ctx.config.merge.sector_resolution,
  );

  const recursionLimit = depth > 10;
  if (recursionLimit) {
    console.info(`(!) Couldn't split ${name} (${features.length} left)`);
  }

  if (features.length <= MAX_ITEMS_PER_DATASET || recursionLimit) {
    // yay, it's small enough
    return { [name]: { features, bbox, sectorIds, ...metadata } };
  }

  // it's not small enough
  const tallerThanWide = bbox.maxLat - bbox.minLat > bbox.maxLng - bbox.minLng;
  if (tallerThanWide) {
    const midway = bbox.minLat + (bbox.maxLat - bbox.minLat) / 2;
    const out: [north: GeoJsonFeature[], south: GeoJsonFeature[]] = [[], []];
    for (const f of features) {
      out[+(getFirstCoord(f.geometry)[1] < midway)]!.push(f);
    }

    const [north, south] = out;

    return {
      ...splitUntilSmallEnough(
        //
        ctx,
        `${name}^N`,
        metadata,
        north,
        depth + 1,
      ),
      ...splitUntilSmallEnough(
        //
        ctx,
        `${name}^S`,
        metadata,
        south,
        depth + 1,
      ),
    };
  }

  // else: it's wider than it is tall
  const midway = bbox.minLng + (bbox.maxLng - bbox.minLng) / 2;
  const out: [east: GeoJsonFeature[], west: GeoJsonFeature[]] = [[], []];
  for (const f of features) {
    out[+(getFirstCoord(f.geometry)[0] < midway)]!.push(f);
  }

  const [east, west] = out;

  return {
    ...splitUntilSmallEnough(
      //
      ctx,
      `${name}^E`,
      metadata,
      east,
      depth + 1,
    ),
    ...splitUntilSmallEnough(
      //
      ctx,
      `${name}^W`,
      metadata,
      west,
      depth + 1,
    ),
  };
}

/** normalizes the weird ^N^S^E names generated by `splitUntilSmallEnough` */
export function normalizeName(
  input: HandlerReturnWithBBox,
): HandlerReturnWithBBox {
  const index: Record<string, number> = {};
  const output: HandlerReturnWithBBox = {};

  for (const name in input) {
    const newName = name.replace(/^([^^]+)(\^\w)+$/, (_, withoutSuffix) => {
      index[withoutSuffix] ||= 0;
      index[withoutSuffix] += 1;
      return `${withoutSuffix} ${index[withoutSuffix]}`;
    });

    output[newName] = input[name]!;
  }
  return output;
}
