name: release-npm

on:
  push:
    branches:
      - main

permissions:
  id-token: write # OIDC
  contents: write # release-please (create commit)
  pull-requests: write # release-please (create PR)

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: release-npm
    concurrency: release-npm

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 26.x

      - run: corepack enable
      - run: pnpm install
      - run: pnpm run -r build

      - name: 🚀 release-please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: node
          manifest-file: .github/release-please-manifest.json
          config-file: .github/release-please-config.json

      - name: 🚀 npm publish (cli)
        if: ${{ steps.release.outputs['packages/cli--release_created'] }}
        working-directory: packages/cli
        run: npm publish --provenance

      - name: 🚀 npm publish (changeset-watcher)
        if: ${{ steps.release.outputs['packages/changeset-watcher--release_created'] }}
        working-directory: packages/changeset-watcher
        run: npm publish --provenance
